project:
  name: "POC Project"

data_source:
  mode: "yahoo"   # yahoo | csv | ib

paths:
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"

symbols:
  - SPY
  - AAPL
  - MSFT

csv:
  file_pattern: "{symbol}.csv"

yahoo:
  period: "2y"
  interval: "1d"
  auto_adjust: false
  save_downloaded_csv: true

ib:
  host: "127.0.0.1"
  port: 7497
  client_id: 1
